### ISSUE TITLE
Coment and  code not matching 

### ISSUE THREAD

**Issue by YadnyeshSawant** [theujwalthakare/JAVA-WORLD#1]
https://github.com/theujwalthakare/JAVA-WORLD/blame/09e78fb6c18f7237b13917093ed8f4704313e300/Basics/JavaOut.java#L5C46-L5C46

Line 5 says println but in comment it is mentioned as print for no new line
Please do check the files before commiting

**Comment by theujwalthakare** [comment]
okay
